use rand::{RngExt, rng};

use super::ServerConfig;
use crate::util::{ALPHA, PASSWORD, generate_random_string};

impl Default for ServerConfig {
  fn default() -> Self {
    let mut rng = rng();

    Self {
      pvp: true,
      pvp_log_tool_chat: true,
      pvp_log_tool_file: true,
      pvp_melee_damage_modifier: 30.0,
      pvp_firearm_damage_modifier: 50.0,
      pvp_melee_while_hit_reaction: false,

      pause_empty: true,
      fast_forward_multiplier: 40.0,
      no_fire: false,
      announce_death: false,
      announce_animal_death: false,
      save_world_every_minutes: 0,
      seed: generate_random_string(16, ALPHA),
      use_physics_hit_reaction: false,

      global_chat: true,
      chat_streams: "s,r,a,w,y,sh,f,all".to_string(),
      chat_message_character_limit: 200,
      chat_message_slow_mode_time: 3,
      server_welcome_message: "Welcome to Project Zomboid Multiplayer! <LINE> <LINE> To interact with the Chat panel: press Tab, T, or Enter. <LINE> <LINE> The Tab key will change the target stream of the message. <LINE> <LINE> Global Streams: /all <LINE> Local Streams: /say, /yell <LINE> Special Steams: /whisper, /safehouse, /faction. <LINE> <LINE> Press the Up arrow to cycle through your message history. Click the Gear icon to customize chat. <LINE> <LINE> Happy surviving!".to_string(),
      discord_enable: false,
      discord_token: "".to_string(),
      discord_chat_channel: "".to_string(),
      discord_log_channel: "".to_string(),
      discord_command_channel: "".to_string(),
      webhook_address: "".to_string(),

      server_player_id: rng.random(),
      reset_id: rng.random(),
      public: false,
      public_name: "My PZ Server".to_string(),
      public_description: "".to_string(),
      mods: "".to_string(),
      workshop_items: "".to_string(),
      map: "Muldraugh, KY".to_string(),
      password: "".to_string(),

      default_port: 16261,
      udp_port: 16262,
      ping_limit: 0,
      max_players: 32,
      max_packets_per_second: 300,
      server_browser_announced_ip: "".to_string(),
      rcon_port: 27015,
      rcon_password: generate_random_string(32, PASSWORD),
      do_lua_checksum: true,
      deny_login_on_overloaded_server: true,
      login_queue_enabled: false,
      login_queue_connect_timeout: 60,
      upnp: true,

      safehouse_prevents_loot_respawn: true,
      player_safehouse: false,
      admin_safehouse: false,
      safehouse_allow_trespass: true,
      safehouse_allow_fire: true,
      safehouse_allow_loot: true,
      safehouse_allow_respawn: false,
      safehouse_day_survived_to_claim: 0,
      safe_house_removal_time: 144,
      safehouse_allow_non_residential: false,
      safehouse_disable_disguises: true,
      max_safezone_size: 20000,
      disable_safehouse_when_owner_connected: false,

      display_user_name: true,
      show_first_and_last_name: false,
      username_disguises: false,
      hide_disguised_user_name: false,
      mouse_over_to_see_display_name: true,
      hide_players_behind_you: true,
      ban_kick_global_sound: true,
      trash_delete_all: false,
      player_bump_player: false,
      map_remote_player_visibility: 1,
      allow_non_ascii_username: false,
      allow_coop: true,
      steam_scoreboard: false,
      show_coordinates: false,
      disable_scoreboard: false,
      hide_admins_in_player_list: false,

      spawn_point: "0,0,0".to_string(),
      spawn_items: "".to_string(),
      switch_zombies_ownership_each_update: false,
      player_respawn_with_self: false,
      player_respawn_with_other: false,
      knocked_down_allowed: false,
      sneak_mode_hide_from_other_players: true,
      ultra_speed_does_not_affect_to_animals: false,

      safety_system: true,
      show_safety: true,
      safety_toggle_timer: 2,
      safety_cooldown_timer: 3,
      safety_disconnect_delay: 60,

      voice_enable: true,
      voice_min_distance: 10.0,
      voice_max_distance: 100.0,
      voice_3d: true,
      speed_limit: 70.0,

      faction: true,
      faction_day_survived_to_create: 0,
      faction_players_required_for_tag: 1,

      disable_vehicle_towing: false,
      disable_trailer_towing: false,
      disable_burnt_towing: false,
      car_engine_attraction_modifier: 0.5,

      war: false,
      war_start_delay: 600,
      war_duration: 3600,
      war_safehouse_hit_points: 3,
      allow_destruction_by_sledgehammer: true,
      sledgehammer_only_in_safehouse: false,

      anti_cheat_safety: 2,
      anti_cheat_speed: 2,
      anti_cheat_no_clip: 4,
      anti_cheat_hit: 2,
      anti_cheat_packet_exception: 4,
      anti_cheat_permission: 2,
      anti_cheat_xp: 2,
      anti_cheat_safe_house: 2,
      anti_cheat_player: 2,
      anti_cheat_checksum: 2,

      bad_word_list_file: "".to_string(),
      good_word_list_file: "".to_string(),
      bad_word_policy: 3,
      bad_word_replacement: "[HIDDEN]".to_string(),
      steam_vac: true,
      drop_off_white_list_after_death: false,

      client_command_filter: "-vehicle.*;+vehicle.damageWindow;+vehicle.fixPart;+vehicle.installPart;+vehicle.uninstallPart".to_string(),
      client_action_logs: "ISEnterVehicle;ISExitVehicle;ISTakeEngineParts;".to_string(),
      perk_logs: true,
      item_numbers_limit_per_container: 0,
      blood_splat_lifespan_days: 0,
      remove_player_corpses_on_corpse_removal: false,
    }
  }
}
